// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mepgyunpgxdkzaxgxgjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lcGd5dW5wZ3hka3pheGd4Z2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjY4MTMsImV4cCI6MjA3MTkwMjgxM30.X5Mq4jiCLbrdLuC2-z4RYZCi9X2MKcvDtByAJNRaHyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});